**Estadística Aplicada**

Sesion 3 - 10 agosto

Paulina Quiroz Sánchez 1723927

Numpy (Numerical Python) ayuda a manejar números en Python (vectores, decimales)

La estructura básica de Numpy son los arreglos (arrays).
Un arreglo es una colección de objetos del mismo tipo.

Vamos a suponer que tenemos las ventas de botellas de agua de la cafetería de la facu.

Lunes 23, Martes 45, Miércoles 34, Jueves 28, Viernes 20

In [8]:
#Instalar la libreria numpy
pip install numpy

SyntaxError: invalid syntax (3628348969.py, line 2)

In [2]:
import numpy as np

In [3]:
ventas = [23,45,34,28,20]

In [4]:
type(ventas)

list

In [9]:
ventas = np.array(ventas)

In [10]:
type(ventas)

numpy.ndarray

In [11]:
#Como ya es un arreglo de numpy ya podemos usar las funciones de numpy
#La primera operación será suma
np.sum(ventas)

150

In [13]:
#Multiplicacion en numpy
np.prod(ventas)

19706400

In [14]:
#Media o promedio
np.mean(ventas)

30.0

In [15]:
#Valor máximo de un array
np.max(ventas)

45

In [16]:
#Valor mínimo de un array
np.min(ventas)

20

In [17]:
#Para ordenar los datos del array
np.sort(ventas)

array([20, 23, 28, 34, 45])

In [18]:
#Calcular la varianza (Varianza población)
np.var(ventas)

78.8

In [19]:
#Desviación estándar (Desviación estándar poblacional)
np.std(ventas)

8.87693640846886

In [20]:
#Varianza muestral (agregar ddof)
np.var(ventas, ddof=1)

98.5

In [21]:
#Desviación estándar muestral (agregar ddof)
np.std(ventas, ddof=1)

9.924716620639604

In [24]:
#Generar un vector  ***Recordar que Python empieza en cero****
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
#Pedire a Python del 10 al 20, recordemos que si le ponemos 20, considerará solo hasta 19
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
#Pedirle a Python del 1 al 100, de 15 en 15
np.arange(1,100, 15)

array([ 1, 16, 31, 46, 61, 76, 91])

In [32]:
##Números aleatorios de una distribución uniforme
np.random.randint(0,25,10)

array([11, 14,  9,  7,  8, 15,  5,  2, 13, 10])

In [36]:
#fijar semilla
np.random.seed(12)
np.random.randint(0,25,10)

array([11,  6, 17,  2,  3,  3, 12, 16, 22, 17])